name: CI/CD Pipeline with Docker Compose

on:
  push:
    branches: [ "develop" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FILE_STORAGE: ${{ secrets.FILE_STORAGE }}

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. .env 파일 생성
      - name: Create .env file
        run: |
          echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env
          echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
          echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> .env
          echo "ALLOWED_ORIGIN=${{ secrets.ALLOWED_ORIGIN }}" >> .env
          echo "FILE_STORAGE=${{ env.FILE_STORAGE }}" >> .env
          echo "HOLIDAY_API_KEY=${{ secrets.HOLIDAY_API_KEY }}" >> .env

      # 3. EC2로 파일 전송
      - name: Copy file to EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./*"
          target: "/home/ubuntu/website/backend"
          rm: true

      # 4. EC2에서 Docker Compose 실행
      - name: Deploy with Docker Compose on EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: FILE_STORAGE
          script: |
            cd /home/ubuntu/website/backend
            mkdir -p $FILE_STORAGE
            chmod 777 $FILE_STORAGE
            
            docker compose down || true
            docker image prune -f
            docker compose up --build -d
            docker compose logs --tail=50